/**
 * Drive Proxy Token Utilities
 *
 * Generates and verifies HMAC tokens for the Google Drive file proxy endpoint.
 * This allows the render task to create signed URLs that Shotstack can fetch,
 * without making Drive files public.
 */

import { createHmac } from 'crypto';

/**
 * Get the secret key for HMAC signing.
 * Uses AGENTUITY_SDK_KEY as the secret (always available in deployment).
 * Falls back to a static dev key for local development.
 */
function getSecret(): string {
	return process.env.AGENTUITY_SDK_KEY || process.env.OPENAI_API_KEY || 'dev-proxy-secret';
}

/**
 * Create an HMAC token for a given Google Drive file ID.
 * The token proves the URL was generated by our render task.
 */
export function createDriveProxyToken(fileId: string): string {
	const hmac = createHmac('sha256', getSecret());
	hmac.update(fileId);
	return hmac.digest('hex').slice(0, 32); // 32 hex chars is plenty
}

/**
 * Verify an HMAC token for a given Google Drive file ID.
 */
export function verifyDriveProxyToken(fileId: string, token: string): boolean {
	const expected = createDriveProxyToken(fileId);
	// Constant-time comparison to prevent timing attacks
	if (expected.length !== token.length) return false;
	let mismatch = 0;
	for (let i = 0; i < expected.length; i++) {
		mismatch |= expected.charCodeAt(i) ^ token.charCodeAt(i);
	}
	return mismatch === 0;
}

/**
 * Build a signed proxy URL for a Google Drive file.
 * Shotstack will fetch from this URL instead of from Google Drive directly.
 *
 * @param appUrl - The application's public URL (e.g., https://my-app.agentuity.run)
 * @param fileId - The Google Drive file ID
 * @returns A signed URL like: https://my-app.agentuity.run/api/drive-file/FILE_ID?token=HMAC
 */
export function buildDriveProxyUrl(appUrl: string, fileId: string): string {
	const token = createDriveProxyToken(fileId);
	// Ensure no double slashes
	const base = appUrl.endsWith('/') ? appUrl.slice(0, -1) : appUrl;
	return `${base}/api/drive-file/${encodeURIComponent(fileId)}?token=${token}`;
}

/**
 * Build a signed proxy URL for a pre-processed local file.
 * Shotstack fetches from this URL to get FFmpeg-enhanced clips
 * (sharpened, speed-ramped) from .temp-cataloger/.
 */
export function buildProcessedFileProxyUrl(appUrl: string, processedId: string): string {
	const token = createDriveProxyToken(processedId);
	const base = appUrl.endsWith('/') ? appUrl.slice(0, -1) : appUrl;
	return `${base}/api/processed-file/${encodeURIComponent(processedId)}?token=${token}`;
}
